trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
  Version: '2.0.$(Build.BuildId)'
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Ormico.DbPatchManager.sln'
    workingDirectory: 'src'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
