trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  system.debug: true
  buildConfiguration: 'Release'
  Version: '2.0.0.$(Build.BuildId)'
steps:
- bash: echo v$(Version)
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
#    projects: 'src/Ormico.DbPatchManager.sln'
    workingDirectory: 'src'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: nuget-artifacts