trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  system.debug: true
  buildConfiguration: 'Release'
  Version: '2.0.$(Build.BuildId)'
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '# Write your commands here
      echo xxxxxxxxxxxxxxxxxx
      echo $(Version)
      echo xxxxxxxxxxxxxxxxxx
      # Use the environment variables input below to pass secret variables to this script'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Ormico.DbPatchManager.sln'
    workingDirectory: 'src'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: nuget-artifacts