trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  system.debug: true
  buildConfiguration: 'Release'
  Version: '2.1.0.$(Build.BuildID)'
steps:
- bash: echo v$(Version)
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Ormico.DbPatchManager.sln'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- bash: dotnet build -c release src/Ormico.DbPatchManager.CLI/Ormico.DbPatchManager.CLI.csproj
- bash: dotnet publish -c release src/Ormico.DbPatchManager.CLI/Ormico.DbPatchManager.CLI.csproj
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: nuget-artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'src/Ormico.DbPatchManager.CLI/bin/release/netcoreapp3.1/publish/'
    artifactName: zip-artifacts
